Cinema.WEB/Areas/Admin/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cinema.BLL.DTO;
using Cinema.BLL.Interfaces;
using Cinema.WEB.Automapper;
using Cinema.WEB.Extensions;
using Cinema.WEB.ViewModels;

namespace Cinema.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class FilmsController : Controller
    {
        private readonly IFilmService _filmService;
        private readonly IFileService _fileService;
        private readonly IGenreService _genreService;

        public FilmsController(IFilmService filmService, IFileService fileService, IGenreService genreService)
        {
            _filmService = filmService;
            _fileService = fileService;
            _genreService = genreService;
        }

        public ActionResult Index()
        {
            var filmsDto = _filmService.GetAll().ToList();
            var filmsViewModel = AutoMapperWeb.GetMapper().Map<List<FilmViewModel>>(filmsDto);
            foreach (var filmViewModel in filmsViewModel)
            {
                filmViewModel.Posters = new List<string>(_fileService.GetFilesByTypeAndId("poster", filmViewModel.Id));
            }
            return View(filmsViewModel);
        }

        public ActionResult Delete(string id)
        {
            var filesToDelete = _fileService.GetFilesByTypeAndId("Poster", id);
            var targetFolder = HttpContext.Server.MapPath("~/Content/Files/Images/Posters");
            foreach (var fileToDelete in filesToDelete)
            {
                var pathToFile = Path.Combine(targetFolder, fileToDelete);
                System.IO.File.Delete(pathToFile);
            }
            _filmService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            ViewBag.Genres = AutoMapperWeb.GetMapper().Map<List<GenreDto>>(_genreService.GetAll());
            var flimViewModel = AutoMapperWeb.GetMapper().Map<FilmViewModel>(_filmService.Get(id));
            return View(flimViewModel);
        }

        [HttpPost]
        public ActionResult Edit(FilmViewModel film, string[] selectedGenres)
        {
            if (!ModelState.IsValid) return View();
            var filmDto = AutoMapperWeb.GetMapper().Map<FilmDto>(film);
            if (selectedGenres != null)
            {
                foreach (var genre in _genreService.GetInId(selectedGenres))
                {
                    filmDto.Genres.Add(genre);
                }
            }
            _filmService.Edit(filmDto);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.Genres = _genreService.GetAll();
            return View();
        }

        [HttpPost]
        public ActionResult Add(FilmViewModel film, HttpPostedFileBase uploadImage, string[] selectedGenres)
        {
            var validatingImageResult = uploadImage.CheckPoster();

            if (ModelState.IsValid  && validatingImageResult == null)
            {
                film.Id = Guid.NewGuid().ToString();

                var image = Image.FromStream(uploadImage.InputStream, true, true);
                var extension = uploadImage.FileName.Substring(uploadImage.FileName.LastIndexOf('.'));
                var targetFolder = HttpContext.Server.MapPath("~/Content/Files/Images/Posters");
                var posterName = film.Name.Trim().Replace(' ', '_').Replace(':','_').ToLower() + "_1";
                var targetPath = Path.Combine(targetFolder,  posterName + extension);

                image.Save(targetPath);

                var posterId = Guid.NewGuid().ToString();
                var poster = new FileDto()
                {
                    Id = posterId,
                    Extension = extension,
                    Name = posterName,
                    Type = "Poster",
                    OwnerId = film.Id
                };
                _fileService.Create(poster);
                var filmDto = AutoMapperWeb.GetMapper().Map<FilmDto>(film);

                if (selectedGenres != null)
                {
                    foreach (var genre in _genreService.GetInId(selectedGenres))
                    {
                        filmDto.Genres.Add(genre);
                    }
                }
                _filmService.Create(filmDto);
                return RedirectToAction("Index");
            }
            @ViewBag.ImageErrorMessage = validatingImageResult;
            return View();
        }
    }
}

Cinema.WEB/Areas/Admin/Controllers/GenresController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Cinema.BLL.DTO;
using Cinema.BLL.Interfaces;
using Cinema.WEB.Automapper;
using Cinema.WEB.ViewModels;

namespace Cinema.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class GenresController : Controller
    {
        private readonly IGenreService _genreService;

        public GenresController(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public ActionResult Index()
        {
            var genresDto = _genreService.GetAll();
            var genres = AutoMapperWeb.GetMapper().Map<List<GenreViewModel>>(genresDto);
            return View(genres);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var genreDto = _genreService.Get(id);
            var genreViewModel = AutoMapperWeb.GetMapper().Map < GenreViewModel>(genreDto);
            return View(genreViewModel);
        }

        [HttpPost]
        public ActionResult Edit(GenreViewModel genre)
        {
            _genreService.Edit(AutoMapperWeb.GetMapper().Map<GenreDto>(genre));
            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id)
        {
            _genreService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(GenreCreateViewModel genre)
        {
            if (!ModelState.IsValid) return View();
            var genreDto = AutoMapperWeb.GetMapper().Map<GenreDto>(genre);
            _genreService.Create(genreDto);
                
            return RedirectToAction("Index");
        }
    }
}

Cinema.WEB/Areas/Admin/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using Cinema.BLL.DTO;
using Cinema.BLL.Interfaces;
using Cinema.WEB.Automapper;
using Cinema.WEB.ViewModels;

namespace Cinema.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class ScheduleController : Controller
    {
        private readonly IFilmService _filmService;
        private readonly IScheduleService _scheduleService;
        private readonly ISessionService _sessionService;

        public ScheduleController(IFilmService filmService, IScheduleService scheduleService, ISessionService sessionService)
        {
            _filmService = filmService;
            _scheduleService = scheduleService;
            _sessionService = sessionService;
        }

        [HttpGet]
        public ActionResult Index(DateTime? date)
        {
            if (date == null)
                date = DateTime.Now;
            var schedulesDto = _scheduleService.GetByDateSchedules((DateTime)date);
            var sessions = new List<SessionDto>();
            schedulesDto.ForEach(s => sessions.AddRange(s.Sessions));

            sessions = sessions.OrderBy(s => s.Time.TimeOfDay).ToList();

            var sessionsViewModel = AutoMapperWeb.GetMapper().Map<List<SessionViewModel>>(sessions);
            foreach (var session in sessionsViewModel)
            {
                var film = _filmService.Get(session.FilmId);
                film.Sessions = null;
                session.FilmViewModel = AutoMapperWeb.GetMapper().Map<FilmViewModel>(film);
            }

            return View(sessionsViewModel);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var currentFilmsDto = _filmService.GetAllBeetwenDates(DateTime.Now, DateTime.Now).ToList();
            var currentFilmsViewModel = AutoMapperWeb.GetMapper().Map<List<FilmViewModel>>(currentFilmsDto);
            ViewBag.currentFilms = currentFilmsViewModel;
            return View();
        }

        [HttpPost]
        public ActionResult Add(ScheduleViewModelCreate schedule)
        {
            if (!ModelState.IsValid) return View();
            var times = Request.Form.GetValues("time[]");
            var films = Request.Form.GetValues("film[]");

            if (times == null || films == null) return RedirectToAction("Index");
            var i = 0;
            foreach (var time in times)
            {
                if (time != "" && films[i] != "")
                {
                    DateTime parseTime;
                    if (DateTime.TryParseExact(time, "HH:mm", CultureInfo.InvariantCulture, DateTimeStyles.None, out parseTime))
                    {
                        schedule.TimeFilm.Add(parseTime, films[i]);
                    }
                }
                i++;
            }
            var scheduleDto = new ScheduleDto
            {
                Id = Guid.NewGuid().ToString(),
                From = schedule.From,
                To = schedule.To
            };
            _scheduleService.Create(scheduleDto);

            foreach (var timeFilm in schedule.TimeFilm)
            {
                var session = new SessionDto
                {
                    Id = Guid.NewGuid().ToString(),
                    FilmId = timeFilm.Value,
                    Time = timeFilm.Key,
                    ScheduleId = scheduleDto.Id
                };
                _sessionService.Create(session);
            }
            return RedirectToAction("Index");
        }

        public JsonResult JsonGetTimes(string rawFromdate, string rawToDate)
        {
            DateTime dateFrom;
            DateTime dateTo;
            if (rawFromdate == null || rawToDate == null)
                return Json("not all items have got", JsonRequestBehavior.AllowGet);
            if (!DateTime.TryParse(rawFromdate, out dateFrom) || !DateTime.TryParse(rawToDate, out dateTo))
            {
                return Json("One of dates is wrong.", JsonRequestBehavior.AllowGet);
            }

            var schedulesDto = _scheduleService.GetBeetwenDates(dateFrom, dateTo);
            var sessions = new List<SessionDto>();

            schedulesDto.ForEach(s => sessions.AddRange(s.Sessions));
            sessions = sessions.OrderBy(s => s.Time.TimeOfDay).ToList();

            foreach (var session in sessions)
            {
                var film = _filmService.Get(session.FilmId);
                film.Sessions = null;
                session.FilmDto = film;
            }

            var timeLine = new Dictionary<string, Dictionary<string, string>>();

            for (var dt = dateFrom; dt <= dateTo; dt = dt.AddDays(1))
            {
                var times = sessions
                    .Where(s => s.ScheduleDto.From <= dt && s.ScheduleDto.To >= dt)
                    .ToDictionary(
                        session => session.Time.ToShortTimeString(), 
                        session => session.Time.AddMinutes(session.FilmDto.Duration).ToShortTimeString());
                timeLine.Add(dt.ToShortDateString(), times);
            }
            return Json(timeLine, JsonRequestBehavior.AllowGet);
        }
    }
}

Cinema.WEB/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <title>
        @ViewBag.Title - Cinema Administration
    </title>
    @Styles.Render("~/Content/css")
    @*@Styles.Render("~/Content/datepicker-air.css")*@
    @RenderSection("Styles", false)
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
@*@Html.Partial("_LoginPartial")*@
<body class="skin-blue">
    <!-- header logo: style can be found in header.less -->
    <header class="header">
        <a href="@Url.Content("~")" class="logo">
            <!-- Add the class icon to your logo image or logo icon to add the margining -->
            Cinema
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="navbar-right">
                <ul class="nav navbar-nav">
                    <!-- Tasks: style can be found in dropdown.less -->
                    <!-- User Account: style can be found in dropdown.less -->
                    @Html.Partial("../Partial/_LoginPartial")
                </ul>
            </div>
        </nav>
    </header>
    <div class="wrapper row-offcanvas row-offcanvas-left">
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="left-side sidebar-offcanvas">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-bar-char"></i> <span>Films</span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Index", "Films")">
                                    <i class="fa fa-dashboard"></i> <span>Films</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Add", "Films")">
                                    <i class="fa fa-dashboard"></i> <span>Add Film</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-bar-char"></i> <span>Genres</span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Index", "Genres")">
                                    <i class="fa fa-dashboard"></i> <span>Genres</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Add", "Genres")">
                                    <i class="fa fa-dashboard"></i> <span>Add Genre</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-bar-char"></i> <span>Schedule</span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Index", "Schedule")">
                                    <i class="fa fa-dashboard"></i> <span>View Schedule by date</span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Add", "Schedule")">
                                    <i class="fa fa-dashboard"></i> <span>Add Schedule</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Right side column. Contains the navbar and content of the page -->
        <aside class="right-side">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>Central administration</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="@Url.Content("~")"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">@ViewBag.Title</li>
                </ol>
            </section>
            <!-- Main content -->
            @RenderBody()
            <!-- /.content -->
        </aside><!-- /.right-side -->
    </div><!-- ./wrapper -->
    <!-- add new calendar event modal -->
    <!-- jQuery 2.1.1 + Jquery UI 1.10.4 -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/custom")*@
    @Scripts.Render("~/bundles/AdminLTE")
    @*@Scripts.Render("~/scripts/datepicker.js")*@
    @Scripts.Render("~/scripts/datepicker.min.js")
    @Scripts.Render("~/scripts/date.js")
    @Scripts.Render("~/scripts/ru-Ru.js")
    @RenderSection("Scripts", false)

    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    @*<script src="../../Content/AdminLTE/js/AdminLTE/dashboard.js" type="text/javascript"></script>*@
    <!-- AdminLTE for demo purposes -->
    @*<script src="../../Content/AdminLTE/js/AdminLTE/demo.js" type="text/javascript"></script>*@
</body>
</html>